# Generated by Django 5.1.7 on 2025-03-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carParkNo', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('xCoord', models.FloatField()),
                ('yCoord', models.FloatField()),
                ('carParkType', models.CharField(max_length=50)),
                ('typeOfParkingSystem', models.CharField(max_length=50)),
                ('shortTermParking', models.CharField(max_length=50)),
                ('freeParking', models.CharField(max_length=50)),
                ('nightParking', models.BooleanField(default=False)),
                ('carParkDecks', models.IntegerField(blank=True, null=True)),
                ('gantryHeight', models.FloatField(blank=True, null=True)),
                ('carParkBasement', models.BooleanField(default=False)),
            ],
        ),
    ]
