# Generated by Django 5.1.7 on 2025-04-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpark',
            name='centralArea',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carpark',
            name='peakHour',
            field=models.BooleanField(default=False),
        ),
    ]
