# Generated by Django 5.1.7 on 2025-04-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapHandler', '0002_carpark_centralarea_carpark_peakhour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpark',
            name='centralArea',
        ),
        migrations.AddField(
            model_name='carpark',
            name='peakHourEnd',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpark',
            name='peakHourStart',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='freeParking',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
    ]
