# Generated by Django 5.1.7 on 2025-04-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapHandler', '0003_remove_carpark_centralarea_carpark_peakhourend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpark',
            name='centralArea',
            field=models.BooleanField(default=False),
        ),
    ]
