# Generated by Django 5.1.7 on 2025-03-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userHandler", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
