# Generated by Django 5.1.7 on 2025-03-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userHandler', '0003_savedlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedlocation',
            options={},
        ),
        migrations.RenameField(
            model_name='savedlocation',
            old_name='created_at',
            new_name='saved_at',
        ),
        migrations.AlterUniqueTogether(
            name='savedlocation',
            unique_together={('user', 'name')},
        ),
        migrations.AddField(
            model_name='savedlocation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedlocation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='savedlocation',
            index=models.Index(fields=['user', 'name'], name='userHandler_user_id_db5de3_idx'),
        ),
        migrations.AddIndex(
            model_name='savedlocation',
            index=models.Index(fields=['user', 'saved_at'], name='userHandler_user_id_0d9df9_idx'),
        ),
        migrations.RemoveField(
            model_name='savedlocation',
            name='updated_at',
        ),
    ]
