# Stage 1: Base build stage
FROM python:3.13-slim AS builder

# Create the app directory
RUN mkdir /app

# Set the working directory
WORKDIR /app

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Upgrade pip and install dependencies
RUN pip install --upgrade pip

# Copy the requirements file first (better caching)
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Production stage
FROM python:3.13-slim

# Create a new user and set the app directory
RUN useradd -m -r appuser && \
    mkdir /app && \
    chown -R appuser:appuser /app

# Copy the Python dependencies from the builder stage
COPY --from=builder /usr/local/lib/python3.13/site-packages/ /usr/local/lib/python3.13/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/

# Set the working directory
WORKDIR /app

# Copy application code and set permissions
COPY --chown=appuser:appuser . .

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Ensure staticfiles directory has correct permissions
RUN mkdir -p /app/staticfiles && chown -R appuser:appuser /app/staticfiles
RUN chown -R appuser:appuser /app/db.sqlite3


# Switch to non-root user
USER appuser

# Expose port and run app
EXPOSE 8000

# Collect static files before running the application
CMD ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py runImportScheduler & gunicorn --bind 0.0.0.0:8000 --workers 3 parkHereWebApp.wsgi:application"]
